" Generated by vim-plug
" Sat Dec 30 14:13:45 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ack.vim'].commit = '36e40f9ec91bdbf6f1adf408522a73a6925c3042'
silent! let g:plugs['alchemist.vim'].commit = '23092f2ffeec33f10eedff3665a500d1ec63f3d0'
silent! let g:plugs['coc.nvim'].commit = '7b9e1ef0a1399907c51d23b6080b94a5aba4a654'
silent! let g:plugs['ctrlp.vim'].commit = '7c972cb19c8544c681ca345c64ec39e04f4651cc'
silent! let g:plugs['nerdcommenter'].commit = 'd2e21d417f6c788b11ae3b90d7ac478930dead36'
silent! let g:plugs['nerdtree'].commit = '32168889bdbc1e7d1d313e3e41c1cc794b38eac5'
silent! let g:plugs['nvim-treesitter'].commit = 'eb96ca52a7e72ec6d45b163e90bcb5e0774d44ad'
silent! let g:plugs['rust.vim'].commit = '889b9a7515db477f4cb6808bef1769e53493c578'
silent! let g:plugs['syntastic'].commit = '8d5e37c29cf5952fbf300b9230bffe424c61a488'
silent! let g:plugs['ultisnips'].commit = 'f6d1501b630cb783b0af8507c5588328f826d40f'
silent! let g:plugs['vim-airline'].commit = 'e6bb8427dc2d2dc3583ed1bf5ff6a9682c854d32'
silent! let g:plugs['vim-airline-themes'].commit = 'dd81554c2231e438f6d0e8056ea38fd0e80ac02a'
silent! let g:plugs['vim-beancount'].commit = '1ceafecbee5bb8a6e4c48a1c9c878b195e3aa526'
silent! let g:plugs['vim-easymotion'].commit = 'b3cfab2a6302b3b39f53d9fd2cd997e1127d7878'
silent! let g:plugs['vim-elixir'].commit = '6dd03f87d825bf0a9f8611eb54076c7952d4f15c'
silent! let g:plugs['vim-endwise'].commit = 'e714ac3bcfd5a90038de49c3254eded7c70ae3c3'
silent! let g:plugs['vim-expand-region'].commit = '966513543de0ddc2d673b5528a056269e7917276'
silent! let g:plugs['vim-fish'].commit = '50b95cbbcd09c046121367d49039710e9dc9c15f'
silent! let g:plugs['vim-fugitive'].commit = '99db68d9b3304580bd383da7aaee05c7a954a344'
silent! let g:plugs['vim-godot'].commit = 'd748a46be5195256f6b2c767ef32de87b05ae8f7'
silent! let g:plugs['vim-prisma'].commit = '95c5b25066efb34c75bce78698baa371fe0ee7c2'
silent! let g:plugs['vim-ruby'].commit = '88f29671b776fff56e5ee554becf34dd2ee1975c'
silent! let g:plugs['vim-signify'].commit = '7d538b77a5a8806e344b057f8846f6d0c035efa9'
silent! let g:plugs['vim-snippets'].commit = 'ccc2fa1529d372f7ac16d5eb07a385a72b50e05d'
silent! let g:plugs['vim-solarized8'].commit = 'bde9cab3d9e9368f0b62f94149ab51607fcb8b68'
silent! let g:plugs['vim-svelte-plugin'].commit = '612b34640919c29b5cf2d85289dbc762b099858a'
silent! let g:plugs['yats.vim'].commit = '2b6950c7143790e6930b8cf32d60c6858a50d47c'

PlugUpdate!

